name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
      - name: Cache SBT
        uses: coursier/cache-action@v3
      - name: Set up cert permissions (1)
        run: chmod 600 world/server.key
      - name: Set up cert permissions (2)
        run: sudo chown 999 world/server.key
      - name: Start up Postgres instances
        run: docker-compose up -d
      - name: Compile (All) and Test/Coverage (Scala 2 Only)
        run: sbt headerCheck +clean coverage test docs/makeSite coverageReport coverageOff +test
      - name: Shut down Postgres instances
        run: docker-compose down
      - name: Upload code coverage data
        run: bash <(curl -s https://codecov.io/bash)
